### ISSUE TITLE
How to fetch textual data from *genai.GenerateContentResponse - Parts interface

### ISSUE THREAD

**Issue by vsumit89** [google/generative-ai-go#29]
I am writing a function which will take *genai.GenerateContentResponse and return the textual data generated.

func getFirstResponse(resp *genai.GenerateContentResponse) {
	for _, value := range resp.Candidates[0].Content.Parts {
           // each value is a Part interface but I am confused how can I use the textual part it contains 
           // I went through the github code and couldn't found out anything significant
	}
}

**Comment by ArsArsArsArs** [comment]
This simple function worked for me, but don't quote me on this
```golang
func retrieveResponce(parts []genai.Part) string {
	var result string
	for _, part := range parts {
		result += fmt.Sprint(part)
	}
	return result
}
```

**Comment by eliben** [comment]
This is shown in the examples in documentation: https://pkg.go.dev/github.com/google/generative-ai-go/genai#example-GenerativeModel.GenerateContent

See the `printResponse` function in that example.

Closing the issue, but feel free to reopen if the answer is insufficient

**Comment by vsumit89** [comment]
Its working @eliben.
I didn't knew that when we use fmt.Print for an interface it runs the underlying String() method that's something which caused confusion. 
Thanks for the answer @eliben

**Comment by Cidan** [comment]
@eliben I don't like this interface -- it's counter intuitive and overly-generic. Any chance we can change this to be inline with how Go generally operates?

**Comment by jba** [comment]
@Cidan You're referring to the fact that `Part` is an interface with various types that implement it?
Some Go packages have that design:
- https://pkg.go.dev/go/types#Type
- https://pkg.go.dev/go/ast#Expr
- https://pkg.go.dev/go/doc/comment#Block

What design would you prefer?

**Comment by Cidan** [comment]
@jba Yes that's right. I don't think I've ever seen an API where a user has to use `fmt.Sprint` to reflect and get a response. The polymorphism here is the wrong design decision at face value.

Ideally, there are different, discrete types for each kind of reply, such as most every other GCP and Google API. In lieu of that, the Interface should at least define methods for functional use of the package to hide complexity from the user, i.e. `Part.String()`. Requiring `fmt.Sprint` is non-obvious and non-standard, i.e. intellisense tools that use `gopls` give no indication as to what to do with a part -- you have to Google (or Gemini!) it (and eventually land here!) to figure it out.

**Comment by jba** [comment]
>  I don't think I've ever seen an API where a user has to use fmt.Sprint to reflect and get a response.

Can you explain this in more detail? I'm not sure what you mean. You shouldn't need either of those things to work with this API. Use a type switch to determine what part you have:
```
switch p := part.(type) {
case genai.Text: ...
case genai.Blob: ...
...
}
```
If that's what's missing, we can add an example. 

> Ideally, there are different, discrete types for each kind of reply

Can you be more specific here? By "reply" do you mean `Part`? There are different types for each kind of `Part`.

**Comment by Cidan** [comment]
Sure!

Let's take a look at a few different packages together from various sources, so I can illustrate what I mean.

Let's start with Gemini's chief competition, GPT. The [most popular](https://pkg.go.dev/github.com/PullRequestInc/go-gpt3) GPT library works has a Message construct which lets you retrieve replies via a chat completion response from a slice of responses, `resp.Choices[0].Message`.

Functionally, this looks like this when using an editor like VSCode + gopls:

![image](https://github.com/google/generative-ai-go/assets/1133628/0f0d8033-202b-468e-aee4-0b816f334277)

Compare this to the experience of using this library (or the Vertex equivalent):

![image](https://github.com/google/generative-ai-go/assets/1133628/b732f0e4-2658-450c-89f7-258fd5332353)

I now have no idea what to do here. There is no hint, intellisense, or otherwise obvious way on how to use a `Part`. A reasonable user at this point would not think to do this without any hints:

![image](https://github.com/google/generative-ai-go/assets/1133628/42a7f155-01ab-4c34-bb0f-e6301d3f1925)

Nor would a type switch be immediately apparent as a solution here -- there is no in-editor guide that "just works". We can take this further and look at various other API's and interfaces provided for both Google and non-Google services and libraries.

Firebase:
![image](https://github.com/google/generative-ai-go/assets/1133628/b37864bc-50b0-4771-a42e-9b67219ace8a)

Secret Manager:
![image](https://github.com/google/generative-ai-go/assets/1133628/ed2ff094-f5ff-4933-9386-edb5b7107ae1)

BBolt:
![image](https://github.com/google/generative-ai-go/assets/1133628/8692391c-210c-4fe5-a72d-7c05fd716901)

Etc.

The point here is usage should be intuitive and straight forward, which currently it's not. A type switch is also not the answer here -- usability of the Part must be front and center.

Clear over clever.

**Comment by Cidan** [comment]
One quick follow-up -- a solution here would be to add a simple set of functions to the Part interface, such as `String()`, `FunctionCall()`, `Type()` and so forth, with comments, so that usage is intuitive.
