### ISSUE TITLE
Proposal to  add error handling in the GenerateContent method

### ISSUE THREAD

**Issue by lll-lll-lll-lll** [google/generative-ai-go#49]
Hi 🖐️

I would like to propose adding error handling for the `parts` arguments of the `GenerateContent` method.

Currently, if an empty string is passed to a field of a `Text` structure, I believe the method may unnecessarily execute the API.

By adding error handling, we can detect this issue and display an appropriate message to the user.

Specifically, I propose adding the following error handling:

Iterate through each element of `parts` in a for loop and return an error if `part.toPart().GetInlineData() ` is nill or  `part.toPart().GetText()` is an empty string.
I believe that adding these error handlings will reduce the number of unnecessary API executions.

If it seems useful, would you like to try submitting a pull request?

Thank you for your consideration.
```go
model := client.GenerativeModel("gemini-1.0-pro")
resp, err := model.GenerateContent(ctx, genai.Text(""))
if err != nil {
log.Fatal(err)
}
```

**Comment by jba** [comment]
Our general rule with these clients is to provide a minimal layer around the service API, leaving all validation to the service. That's particularly important because the service can change behavior. For example, who's to say that Gemini won't accept an empty prompt and produce some sort of output? I (as client author) wouldn't want to remove that possibility by treating an empty prompt as an error.

**Comment by lll-lll-lll-lll** [comment]
I see. I was not aware of this general approach before. Thank you for your review!
